### ISSUE TITLE
The first layer input of the transformer decoder of the dinosaur model, or kqv

### ISSUE THREAD

**Issue by tangpanyu** [amazon-science/object-centric-learning-framework#10]
I'm sorry that it's difficult for me to read the details of the implementation in the paper through you, so I would like to ask you what is the input of the transfomer decoder? What is the kqv of the attention mechanism in the first layer decoder block?

**Comment by ExpectationMax** [comment]
Hi tangpanyu,

the decoder is trained similar to a next word prediction model with teacher forcing. I.e. it should always predict the next token conditional on the memory (in our case object slots) and the previous gt tokens while accounting for causal masking. As mentioned in the paper, this is similar to the decoder used in [SLATE](https://sites.google.com/view/slate-autoencoder). You can also take a look at the [AutoregressivePatchDecoder](https://amazon-science.github.io/object-centric-learning-framework/api/ocl/decoding/#ocl.decoding.AutoregressivePatchDecoder) in the docs.
Hope that helps!
