### ISSUE TITLE
Reproducing results for movi_c dataset

### ISSUE THREAD

**Issue by dido1998** [amazon-science/object-centric-learning-framework#17]
Hello, I am trying to reproduce results for the movi_c dataset from the dinosaur paper https://openreview.net/forum?id=b9tUk-f_aG. For this I ran the code with this config file https://github.com/amazon-science/object-centric-learning-framework/blob/main/configs/experiment/projects/bridging/dinosaur/movi_c_feat_rec.yaml but I am getting a much lower performance than in the paper. The only change I made was running on 1 gpu instead of 8 due to lack of compute. I wonder if I am missing something?
![W B Chart 8_14_2023, 2_04_50 PM](https://github.com/amazon-science/object-centric-learning-framework/assets/20562351/8ae26e74-7a29-49f0-a6ed-156349eb610f)

**Comment by mseitzer** [comment]
Hi,

thanks for reaching out! It looks like the MOVi configs are mistakenly not using pretrained ViTs. You can change that by modifying the feature_extractor section as follows: 

```
  feature_extractor:
    model_name: vit_small_patch8_224_dino
    pretrained: ${when_testing:false,true}
    freeze: true
```
as it is for the COCO configs (e.g. https://github.com/amazon-science/object-centric-learning-framework/blob/main/configs/experiment/projects/bridging/dinosaur/coco_feat_rec_dino_base16_auto.yaml).

Aside from that, I would recommend increasing the batch size from 8. The model is pretty light on memory, so you may be able to fit batch size 32 or 64 even on a single GPU (depending on your GPU of course).

**Comment by dido1998** [comment]
Thanks! I was able to get the same performance as the paper with the above change.

**Comment by Bontempogianpaolo1** [comment]
Hi @dido1998 ,
How did you plot this metric? The code plots only mse...
